// This is a skeleton starter React page generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import * as ph from "@plasmicapp/host";

import { ScreenVariantProvider } from "../../components/plasmic/devocional/PlasmicGlobalVariant__Screen";
import { PlasmicDevocional } from "../../components/plasmic/devocional/PlasmicDevocional";
import { useRouter } from "next/router";
import { supabase } from "../../components/supabase/supabase";

function Devocional() {
  const router = useRouter();
  const { pid } = router.query;
  const [comment, setComment] = React.useState("");
  const onSend = async () => {
    const { data: user, error } = await supabase.auth.getUser();
    console.log(user);
    if (error) {
      //show error toast
      return ;
    }
    const { data: profile, error: errorProfile } = 
      await supabase.from("profiles").select().filter("email", "eq", user.user.email);
    if (errorProfile || profile.length !== 1) {
      //show error toast
      return ;
    }
    const { error: insertError } = await supabase.from("comments").insert({
      author_id: profile[0].id,
      text: comment,
      date: new Date(Date.now()),
      post_id: pid
    });
    if (insertError) {
      //show error toast;
      return ;
    }
    router.reload();
  }
  return (
    <ph.PageParamsProvider
      params={useRouter()?.query}
      query={useRouter()?.query}
    >
      <PlasmicDevocional 
        send={{
          onClick: onSend
        }}
        textArea={{
          value: comment,
          onChange: (val) => setComment(val)
        }}
      />
    </ph.PageParamsProvider>
  );
}

export default Devocional;
