// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: gerk99sqDLqAi3xSqDhGNs
// Component: az5Tv6-qkFR
import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import { SupabaseFetcher } from "../../supabase/supabase"; // plasmic-import: HX-SzYOed0/codeComponent
import Comment from "../../Comment"; // plasmic-import: d1IXvSf1Cl/component

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic_devocional.module.css"; // plasmic-import: gerk99sqDLqAi3xSqDhGNs/projectcss
import sty from "./PlasmicPost.module.css"; // plasmic-import: az5Tv6-qkFR/css

import LikeIcon from "./icons/PlasmicIcon__Like"; // plasmic-import: E0yJQNlPk9/icon
import CommentIcon from "./icons/PlasmicIcon__Comment"; // plasmic-import: X_VrYnSbgs/icon

export type PlasmicPost__VariantMembers = {};

export type PlasmicPost__VariantsArgs = {};
type VariantPropType = keyof PlasmicPost__VariantsArgs;
export const PlasmicPost__VariantProps = new Array<VariantPropType>();

export type PlasmicPost__ArgsType = {
  pid?: string;
};

type ArgPropType = keyof PlasmicPost__ArgsType;
export const PlasmicPost__ArgProps = new Array<ArgPropType>("pid");

export type PlasmicPost__OverridesType = {
  root?: p.Flex<"div">;
  link?: p.Flex<"a"> & Partial<LinkProps>;
  comment?: p.Flex<typeof Comment>;
};

export interface DefaultPostProps {
  pid?: string;
  className?: string;
}

function PlasmicPost__RenderFunc(props: {
  variants: PlasmicPost__VariantsArgs;
  args: PlasmicPost__ArgsType;
  overrides: PlasmicPost__OverridesType;

  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(
    () =>
      Object.assign(
        {
          pid: "5" as const
        },
        props.args
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const currentUser = p.useCurrentUser?.() || {};

  const [$queries, setDollarQueries] = React.useState({});

  return (
    true ? (
      <div
        data-plasmic-name={"root"}
        data-plasmic-override={overrides.root}
        data-plasmic-root={true}
        data-plasmic-for-node={forNode}
        className={classNames(
          projectcss.all,
          projectcss.root_reset,
          projectcss.plasmic_default_styles,
          projectcss.plasmic_mixins,
          projectcss.plasmic_tokens,
          sty.root
        )}
      >
        <SupabaseFetcher
          className={classNames("__wab_instance", sty.supabaseFetcher__uGttu)}
          filters={(() => {
            try {
              return [
                {
                  column: "id",
                  operator: "eq",
                  value: $props.pid
                }
              ];
            } catch (e) {
              if (e instanceof TypeError) {
                return undefined;
              }
              throw e;
            }
          })()}
          table={"posts" as const}
        >
          <ph.DataCtxReader>
            {$ctx => (
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__rbzNj)}
              >
                {true ? (
                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__lInOb)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__gm0B4)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__rppCh
                        )}
                      >
                        {"Palavra do Beda"}
                      </div>
                    </div>

                    <div
                      className={classNames(projectcss.all, sty.freeBox__kstdr)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text___4R1QZ
                        )}
                      >
                        {(() => {
                          try {
                            return $ctx.supabase[0].title;
                          } catch (e) {
                            if (e instanceof TypeError) {
                              return "Titulo";
                            }
                            throw e;
                          }
                        })()}
                      </div>
                    </div>

                    <div
                      className={classNames(
                        projectcss.all,
                        sty.freeBox___6Obqd
                      )}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__sFEcF
                        )}
                      >
                        {(() => {
                          try {
                            return $ctx.supabase[0].text;
                          } catch (e) {
                            if (e instanceof TypeError) {
                              return "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.";
                            }
                            throw e;
                          }
                        })()}
                      </div>
                    </div>
                  </p.Stack>
                ) : null}
                {true ? (
                  <div
                    className={classNames(projectcss.all, sty.freeBox__mUf1)}
                  >
                    <p.Stack
                      as={"div"}
                      hasGap={true}
                      className={classNames(
                        projectcss.all,
                        sty.freeBox___93Wdc
                      )}
                    >
                      {true ? (
                        <p.Stack
                          as={"div"}
                          hasGap={true}
                          className={classNames(
                            projectcss.all,
                            sty.freeBox___2LWq
                          )}
                        >
                          <LikeIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg___6OaGh
                            )}
                            role={"img"}
                          />

                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__jN30V
                            )}
                          >
                            {"Curtir"}
                          </div>
                        </p.Stack>
                      ) : null}
                      {true ? (
                        <p.Stack
                          as={p.PlasmicLink}
                          data-plasmic-name={"link"}
                          data-plasmic-override={overrides.link}
                          hasGap={true}
                          className={classNames(
                            projectcss.all,
                            projectcss.a,
                            sty.link
                          )}
                          component={Link}
                          href={`/devocional/${(() => {
                            try {
                              return $props.pid;
                            } catch (e) {
                              if (e instanceof TypeError) {
                                return undefined;
                              }
                              throw e;
                            }
                          })()}`}
                          platform={"nextjs"}
                        >
                          <CommentIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg__g1Int
                            )}
                            role={"img"}
                          />

                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__r0Npy
                            )}
                          >
                            {"Comentar"}
                          </div>
                        </p.Stack>
                      ) : null}
                    </p.Stack>

                    <div
                      className={classNames(projectcss.all, sty.freeBox__n0PW)}
                    >
                      <SupabaseFetcher
                        className={classNames(
                          "__wab_instance",
                          sty.supabaseFetcher__yzI33
                        )}
                        filters={(() => {
                          try {
                            return [
                              {
                                column: "post_id",
                                operator: "eq",
                                value: $props.pid
                              }
                            ];
                          } catch (e) {
                            if (e instanceof TypeError) {
                              return undefined;
                            }
                            throw e;
                          }
                        })()}
                        table={"comments" as const}
                      >
                        <ph.DataCtxReader>
                          {$ctx =>
                            (
                              (() => {
                                try {
                                  return $ctx.supabase;
                                } catch (e) {
                                  if (e instanceof TypeError) {
                                    return [];
                                  }
                                  throw e;
                                }
                              })() ?? []
                            ).map((currentItem, currentIndex) => (
                              <Comment
                                data-plasmic-name={"comment"}
                                data-plasmic-override={overrides.comment}
                                cid={(() => {
                                  try {
                                    return currentItem.id;
                                  } catch (e) {
                                    if (e instanceof TypeError) {
                                      return undefined;
                                    }
                                    throw e;
                                  }
                                })()}
                                className={classNames(
                                  "__wab_instance",
                                  sty.comment
                                )}
                                key={currentIndex}
                              />
                            ))
                          }
                        </ph.DataCtxReader>
                      </SupabaseFetcher>
                    </div>
                  </div>
                ) : null}
              </p.Stack>
            )}
          </ph.DataCtxReader>
        </SupabaseFetcher>
      </div>
    ) : null
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "link", "comment"],
  link: ["link"],
  comment: ["comment"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
  link: "a";
  comment: typeof Comment;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicPost__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicPost__VariantsArgs;
    args?: PlasmicPost__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicPost__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicPost__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicPost__ArgProps,
          internalVariantPropNames: PlasmicPost__VariantProps
        }),
      [props, nodeName]
    );

    return PlasmicPost__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicPost";
  } else {
    func.displayName = `PlasmicPost.${nodeName}`;
  }
  return func;
}

export const PlasmicPost = Object.assign(
  // Top-level PlasmicPost renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    link: makeNodeComponent("link"),
    comment: makeNodeComponent("comment"),

    // Metadata about props expected for PlasmicPost
    internalVariantProps: PlasmicPost__VariantProps,
    internalArgProps: PlasmicPost__ArgProps
  }
);

export default PlasmicPost;
/* prettier-ignore-end */
