// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: gerk99sqDLqAi3xSqDhGNs
// Component: b-yBAoSFVG
import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic_devocional.module.css"; // plasmic-import: gerk99sqDLqAi3xSqDhGNs/projectcss
import sty from "./PlasmicSpaceForFixed.module.css"; // plasmic-import: b-yBAoSFVG/css

export type PlasmicSpaceForFixed__VariantMembers = {};

export type PlasmicSpaceForFixed__VariantsArgs = {};
type VariantPropType = keyof PlasmicSpaceForFixed__VariantsArgs;
export const PlasmicSpaceForFixed__VariantProps = new Array<VariantPropType>();

export type PlasmicSpaceForFixed__ArgsType = {
  height?: number;
};

type ArgPropType = keyof PlasmicSpaceForFixed__ArgsType;
export const PlasmicSpaceForFixed__ArgProps = new Array<ArgPropType>("height");

export type PlasmicSpaceForFixed__OverridesType = {
  root?: p.Flex<"div">;
};

export interface DefaultSpaceForFixedProps {
  height?: number;
  className?: string;
}

function PlasmicSpaceForFixed__RenderFunc(props: {
  variants: PlasmicSpaceForFixed__VariantsArgs;
  args: PlasmicSpaceForFixed__ArgsType;
  overrides: PlasmicSpaceForFixed__OverridesType;

  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(
    () =>
      Object.assign(
        {
          height: 50 as const
        },
        props.args
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const currentUser = p.useCurrentUser?.() || {};

  const [$queries, setDollarQueries] = React.useState({});

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        sty.root
      )}
      style={(() => {
        try {
          return {
            height: `${$props.height}px`
          };
        } catch (e) {
          if (e instanceof TypeError) {
            return undefined;
          }
          throw e;
        }
      })()}
    />
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicSpaceForFixed__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicSpaceForFixed__VariantsArgs;
    args?: PlasmicSpaceForFixed__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicSpaceForFixed__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicSpaceForFixed__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicSpaceForFixed__ArgProps,
          internalVariantPropNames: PlasmicSpaceForFixed__VariantProps
        }),
      [props, nodeName]
    );

    return PlasmicSpaceForFixed__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicSpaceForFixed";
  } else {
    func.displayName = `PlasmicSpaceForFixed.${nodeName}`;
  }
  return func;
}

export const PlasmicSpaceForFixed = Object.assign(
  // Top-level PlasmicSpaceForFixed renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements

    // Metadata about props expected for PlasmicSpaceForFixed
    internalVariantProps: PlasmicSpaceForFixed__VariantProps,
    internalArgProps: PlasmicSpaceForFixed__ArgProps
  }
);

export default PlasmicSpaceForFixed;
/* prettier-ignore-end */
