// This is a skeleton starter React component generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import {
  PlasmicAvatarMenu,
  DefaultAvatarMenuProps
} from "./plasmic/devocional/PlasmicAvatarMenu";
import { HTMLElementRefOf } from "@plasmicapp/react-web";
import { supabase } from "./supabase/supabase";
import { useRouter } from "next/router";

export interface AvatarMenuProps extends DefaultAvatarMenuProps {}

function AvatarMenu_(props: AvatarMenuProps, ref: HTMLElementRefOf<"div">) {
  const router = useRouter();
  const onLogout = async() => {
    const { error } = await supabase.auth.signOut();
    if (error === null) {
      router.push("/login")
    }
  }

  return <PlasmicAvatarMenu 
    root={{ ref }} 
    {...props} 
    logout={{
      onClick: onLogout
    }}
  />;
}

const AvatarMenu = React.forwardRef(AvatarMenu_);
export default AvatarMenu;
