// This is a skeleton starter React page generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import * as ph from "@plasmicapp/host";

import { ScreenVariantProvider } from "../components/plasmic/devocional/PlasmicGlobalVariant__Screen";
import { PlasmicHomepage } from "../components/plasmic/devocional/PlasmicHomepage";
import { useRouter } from "next/router";
import AvatarMenu from "../components/AvatarMenu";
import { Session } from "@supabase/supabase-js";
import { supabase } from "../components/supabase/supabase";
import { useIsLoggedIn } from "../components/hooks";

function Homepage() {
  
  useIsLoggedIn();
  return (
    <ph.PageParamsProvider
      params={useRouter()?.query}
      query={useRouter()?.query}
    >
      <PlasmicHomepage
      />
    </ph.PageParamsProvider>
  );
}

export default Homepage;
